name: 04-using-actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Install Dependencies
              run: npm ci
    # checkout the code from the repository
    #install dependencies of our react application
    #execute automated tests
