name: 04-using-actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/react-app
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Install Dependencies
              run: npm ci
            - name: Run Unit Tests
              run: npm run test
    # checkout the code from the repository
    #install dependencies of our react application
    #execute automated tests
