name: 04-using-actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Priniting Folders
              run: ls
    # checkout the code from the repository
    #install dependencies of our react application
    #execute automated tests
